---
title: "FiveThirtyEight Election Forcast 2020 — Rework" 
author: "Cédric Scherer"
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    highlight: kate
    code_folding: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", dpi = 1000, retina = 1)
```

Source: [FiveThirtyEight Election Forcast 2020](https://projects.fivethirtyeight.com/2020-election-forecast/)


## Preparation

```{r}
library(tidyverse)

colors <- c("#606FAF", "#E4544B")
bg <- "#F0EFEF"

theme_set(theme_minimal(base_size = 14, base_family = "Familjen Grotesk"))
theme_update(
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  plot.background = element_rect(color = bg, fill = bg),
  axis.text = element_text(family = "DecimaMonoPro", color = "#999999"),
  axis.title = element_text(size = rel(.9)),
  plot.title = element_text(face = "bold", hjust = .5, size = rel(1.7), margin = margin(b = 10)),
  plot.subtitle = element_text(hjust = .5, size = rel(1.05), margin = margin(b = 15)), 
  legend.position = "none"
)

invisible(Sys.setlocale("LC_TIME", "C"))
```



## Distributions of Simulation Results for Electoral Votes

```{r dist-electoral-v1, fig.width=8, fig.height=9}
df_votes <- readr::read_csv(here::here("data", "electoral_votes.csv"))

df_votes <- 
  df_votes %>% 
  mutate(
    lab = if_else(candidate == "Trump", "&uarr;\nMore\nlikely", ""),
    candidate = if_else(
      candidate == "Biden", "<b style='color:#606FAF;'>Biden</b> wins &rarr;",
                            "<b style='color:#E4544B;'>Trump</b> wins &rarr;"
    ),
    candidate = fct_rev(candidate)
  )

ggplot(df_votes, aes(x = evs, y = chance, fill = candidate)) + 
  geom_col(alpha = .7) +
  geom_line(
    aes(y = zoo::rollmean(chance, 15, na.pad = TRUE)), 
    color = "white", size = 3
  ) +
  geom_hline(yintercept = 0) +
  geom_line(
    aes(y = zoo::rollmean(chance, 15, na.pad = TRUE), color = candidate), 
    size = 1.4
  ) +
  annotate(
    geom = "rect", xmin = -Inf, xmax = 270,
    ymin = -Inf, ymax = Inf, fill = bg, alpha = .5
  ) +
  geom_vline(xintercept = 270) +
  geom_text(
    aes(x = 50, y = .7, label = lab), 
    hjust = .5, family = "Familjen Grotesk", fontface = "italic",
    lineheight = .9, stat = "unique"
  ) +
  facet_wrap(~candidate, ncol = 1, scales = "free_x") + 
  scale_x_continuous(limits = range(df_votes$evs)) +
  scale_y_continuous(guide = "none") +
  scale_color_manual(values = rev(colors)) +
  scale_fill_manual(values = rev(colors)) +
  coord_cartesian(expand = FALSE, ylim = c(NA, 2)) +
  #coord_cartesian(expand = FALSE, clip = "off") +
  labs(
    x = NULL, y = NULL, 
    title = "Every outcome in our simulations",
    subtitle = "All possible Electoral College outcomes for each candidate, with higher bars\nshowing outcomes that appeared more often in our 40,000 simulations"
  ) +
  theme(strip.text = ggtext::element_textbox(size = 15, face = "italic", margin = margin(l = 100)))

ggsave("dist-electoral-v1.png", width = 8, height = 9)
```

```{r dist-electoral-v2, fig.width=8, fig.height=9}
df_votes_expanded <- readr::read_csv(here::here("data", "electoral_votes_expanded.csv"))

df_votes_expanded <- 
  df_votes_expanded %>% 
  mutate(
    lab = if_else(candidate == "Trump", "&uarr;\nMore\nlikely", ""),
    candidate = if_else(
      candidate == "Biden", "<b style='color:#606FAF;'>Biden</b> wins &rarr;",
                            "<b style='color:#E4544B;'>Trump</b> wins &rarr;"
    ),
    candidate = fct_rev(candidate)
  )

ggplot(df_votes_expanded, aes(x = evs, fill = candidate)) + 
  geom_histogram(aes(y = after_stat(density)), binwidth = 1, alpha = .7) +
  geom_line(stat = "density", color = "white", size = 3, adjust = 1.5) +
  geom_hline(yintercept = 0) +
  geom_line(stat = "density", aes(color = candidate), size = 1.4, adjust = 1.5) +
  annotate(
    geom = "rect", xmin = -Inf, xmax = 270, 
    ymin = -Inf, ymax = Inf, fill = bg, alpha = .5
  ) +
  geom_vline(xintercept = 270) +
  geom_text(
    aes(x = 50, y = .007, label = lab), 
    hjust = .5, family = "Familjen Grotesk", fontface = "italic",
    lineheight = .9, stat = "unique"
  ) +
  facet_wrap(~candidate, ncol = 1, scales = "free_x") + 
  scale_x_continuous(limits = range(df_votes$evs)) +
  scale_y_continuous(guide = "none") +
  scale_color_manual(values = rev(colors)) +
  scale_fill_manual(values = rev(colors)) +
  coord_cartesian(expand = FALSE, ylim = c(NA, .02)) +
  #coord_cartesian(expand = FALSE, clip = "off") +
  labs(
    x = NULL, y = NULL, 
    title = "Every outcome in our simulations",
    subtitle = "All possible Electoral College outcomes for each candidate, with higher bars\nshowing outcomes that appeared more often in our 40,000 simulations"
  ) +
  theme(strip.text = ggtext::element_textbox(size = 15, face = "italic", margin = margin(l = 100)))

ggsave("dist-electoral-v2.png", width = 8, height = 9)
```



## Probabilities over Time

```{r}
df_probs <- readr::read_csv(here::here("data", "probability_over_time.csv"))
```

### Chance of Winning

```{r time-chance, fig.width=8, fig.height=5}
ggplot(df_probs, aes(x = date, y = winprob, color = candidate, fill = candidate)) + 
  geom_line(color = "white", size = 3) + 
  geom_line(size = .9) + 
  #geom_step(size = .9) + 
  geom_point(
    data = filter(df_probs, date == max(date)),
    shape = 21, color = "white", stroke = 1.2, size = 3.5
  ) +
  geom_text(
    data = filter(df_probs, date == max(date)),
    aes(label = paste0(" ", round(winprob, 0), "\n in\n 100")), 
    family = "DecimaMonoPro", lineheight = .8, size = 4.5, hjust = 0
  ) +
  scale_x_date(date_labels = "%b. 1", expand = c(0, 0)) +
  scale_y_continuous(
    labels = scales::label_percent(scale = 1), limits = c(0, 100), breaks = 0:5*20
  ) +
  scale_color_manual(values = colors) + 
  scale_fill_manual(values = colors) + 
  coord_cartesian(clip = "off") +
  labs(
    x = NULL, y = NULL, 
    title = "How the forecast has changed",
    subtitle = "The forecast for chances of winning."
  ) +
  theme(
    panel.grid.major.y = element_line(color = "grey85", size = .3),
    axis.ticks.x = element_line(color = "#999999", size = .3),
    axis.ticks.length.x = unit(.3, "lines"),
    plot.margin = margin(20, 45, 20, 20)
  )

ggsave("time-chance.png", width = 8, height = 5)
```

### Electoral Votes

```{r time-electoral, fig.width=8, fig.height=5}
ggplot(df_probs, aes(x = date, y = electoral_votes_avg, 
                     color = candidate, group = candidate)) + 
  geom_ribbon(
    aes(fill = candidate, ymin = electoral_votes_lwr, ymax = electoral_votes_upr), 
    alpha = .15, color = "transparent"
  ) +
  geom_line(color = "white", size = 3) + 
  geom_line(size = 1.4) + 
  geom_point(
    data = filter(df_probs, date == max(date)), aes(fill = candidate), 
    shape = 21, color = "white", stroke = 1.2, size = 3.5
  ) +
  geom_text(
    data = filter(df_probs, date == max(date)),
    aes(label = paste0(" ", round(electoral_votes_avg, 0))), 
    family = "DecimaMonoPro", size = 4.5, hjust = 0
  ) +
  scale_x_date(date_labels = "%b. 1") +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) + 
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(
    x = NULL, y = NULL, 
    title = "How the forecast has changed",
    subtitle = "The forecast for electoral votes."
  ) +
  theme(
    panel.grid.major.y = element_line(color = "grey85", size = .3),
    axis.ticks.x = element_line(color = "#999999", size = .3),
    axis.ticks.length.x = unit(.3, "lines"),
    plot.margin = margin(20, 45, 20, 20)
  )

ggsave("time-electoral.png", width = 8, height = 5)
```

### Popular Votes

```{r time-popular, fig.width=8, fig.height=5}
ggplot(df_probs, aes(x = date, y = popular_votes_avg, 
                     color = candidate, group = candidate)) + 
  geom_ribbon(
    aes(fill = candidate, ymin = popular_votes_lwr, ymax = popular_votes_upr), 
    alpha = .15, color = "transparent"
  ) +
  geom_line(color = "white", size = 3) + 
  geom_line(size = 1.4) + 
  geom_point(
    data = filter(df_probs, date == max(date)), aes(fill = candidate), 
    shape = 21, color = "white", stroke = 1.2, size = 3.5
  ) +
  geom_text(
    data = filter(df_probs, date == max(date)),
    aes(label = paste0(" ", round(popular_votes_avg, 1), "%")), 
    family = "DecimaMonoPro", size = 4.5,
    hjust = 0
  ) +
  scale_x_date(date_labels = "%b. 1") +
  scale_y_continuous(
    labels = scales::label_percent(scale = 1), breaks = seq(42, 58, by = 2)
  ) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) + 
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(
    x = NULL, y = NULL, 
    title = "How the forecast has changed",
    subtitle = "The forecast for popular vote."
  ) +
  theme(
    panel.grid.major.y = element_line(color = "grey85", size = .3),
    axis.ticks.x = element_line(color = "#999999", size = .3),
    axis.ticks.length.x = unit(.3, "lines"),
    plot.margin = margin(20, 55, 20, 20)
  )

ggsave("time-popular.png", width = 8, height = 5)
```



## Maps Simulation Outcomes (Small Multiples)

```{r}
df_simus <- readr::read_csv(here::here("data", "simulations.csv"))

## exploration
ggplot(df_simus, aes(y = fct_rev(factor(state)), fill = winner)) + 
  geom_bar() + 
  scale_fill_manual(values = colors) + 
  coord_cartesian(expand = FALSE) +
  labs(x = "Number of simulation outcomes", y = NULL, fill = "Winner:")


ggplot(df_simus, aes(y = fct_rev(factor(sim)), fill = winner)) + 
  geom_bar() + 
  scale_fill_manual(values = colors) + 
  coord_cartesian(expand = FALSE, clip = "off") +
  labs(x = "Number of states won", y = "Simulation", fill = "Winner:")
```

```{r faceted-map, fig.width=17, fig.height=8}
library(usmap)

df_states <- df_simus %>% 
  select(-abbr) %>% 
  left_join(
    usmap::us_map(regions = "states") %>% 
      rename(state = full) %>% 
      select(-abbr)
  ) %>%
  mutate(
    winner_color = case_when(
      winner_overall == "Trump" & winner == "Trump" ~ colors[2],
      winner_overall == "Trump" & winner == "Biden" ~ "white",
      winner_overall == "Biden" & winner == "Trump" ~ "white",
      winner_overall == "Biden" & winner == "Biden" ~ colors[1]
    ),
    map_label = case_when(
      winner_overall == "Trump" ~ " A TRUMP WIN!",
      winner_overall == "Biden" ~ " A BIDEN WIN!"
    )
  )

ggplot() + 
  geom_polygon(
    data = df_states, 
    aes(x = x, y = y, group = group),
    color = "black", fill = "white", size = .8
  ) +
  geom_polygon(
    data = df_states, 
    aes(x = x, y = y, fill = winner_color, group = group),
    color = "grey85", size = .2
  ) +
  geom_text(
    data = df_states, x = median(df_states$x), y = min(df_states$y), 
    aes(label = map_label,color = map_label), family = "DecimaMonoPro"
  ) +
  facet_wrap(~sim, ncol = 6) +
  coord_fixed() +
  scale_fill_manual(name = NULL, values = c(colors, "white")) +
  scale_color_manual(name = NULL, values = c(colors))+
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    strip.text = element_blank(),
    panel.spacing = unit(1, "lines"),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )

ggsave("faceted-map.png", width = 17, height = 8, bg = bg)
```

